github:
  description: "Apache XML Graphics FOP PDF Images"
  homepage: https://xmlgraphics.apache.org/fop/
  labels:
    - fop
    - apache
  enabled_merge_buttons:
    merge:   false      # disable non-squashing merge
    squash:  true
    rebase:  true
  protected_branches:
    main:
      required_linear_history: true
      required_signatures: false
  dependabot_alerts:  true
  dependabot_updates: false

notifications:
  commits: commits@xmlgraphics.apache.org
  # issues: fop-dev@xmlgraphics.apache.org
  # pullrequests: fop-dev@xmlgraphics.apache.org
  # jobs: fop-dev@xmlgraphics.apache.org
  jira_options: link label
